# Activation de ModSecurity
SecRuleEngine DetectionOnly
# ↑ Passe à "On" une fois que tu as vérifié qu'il n'y a pas de faux positifs

# Logs
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLog /var/log/modsecurity/modsec_audit.log
SecAuditLogFormat JSON

# Corps des requêtes
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject

# Corps des réponses
SecResponseBodyAccess On
SecResponseBodyLimit 524288
SecResponseBodyLimitAction ProcessPartial

# Fichiers temporaires
SecTmpDir /tmp/modsecurity/tmp
SecDataDir /tmp/modsecurity/data
SecUploadDir /tmp/modsecurity/upload

# Divers
SecArgumentSeparator &
SecCookieFormat 0
SecUnicodeMapFile unicode.mapping 20127
SecStatusEngine On

# Niveau de debug (0 = off, 9 = max)
SecDebugLogLevel 0
