/**
 * Auth Service API
 * Authentication Service for the Transcendence Pong application. Handles JWT tokens, OAuth2/SSO, and session management. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Disable2FARequest model module.
 * @module model/Disable2FARequest
 * @version 1.0.0
 */
class Disable2FARequest {
    /**
     * Constructs a new <code>Disable2FARequest</code>.
     * @alias module:model/Disable2FARequest
     * @param code {String} Current 6-digit TOTP code
     * @param password {String} Current password for confirmation
     */
    constructor(code, password) { 
        
        Disable2FARequest.initialize(this, code, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, password) { 
        obj['code'] = code;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>Disable2FARequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Disable2FARequest} obj Optional instance to populate.
     * @return {module:model/Disable2FARequest} The populated <code>Disable2FARequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Disable2FARequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Disable2FARequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Disable2FARequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Disable2FARequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

Disable2FARequest.RequiredProperties = ["code", "password"];

/**
 * Current 6-digit TOTP code
 * @member {String} code
 */
Disable2FARequest.prototype['code'] = undefined;

/**
 * Current password for confirmation
 * @member {String} password
 */
Disable2FARequest.prototype['password'] = undefined;






export default Disable2FARequest;

