/**
 * Auth Service API
 * Authentication Service for the Transcendence Pong application. Handles JWT tokens, OAuth2/SSO, and session management. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Session from './Session';

/**
 * The ListSessions200Response model module.
 * @module model/ListSessions200Response
 * @version 1.0.0
 */
class ListSessions200Response {
    /**
     * Constructs a new <code>ListSessions200Response</code>.
     * @alias module:model/ListSessions200Response
     */
    constructor() { 
        
        ListSessions200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListSessions200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListSessions200Response} obj Optional instance to populate.
     * @return {module:model/ListSessions200Response} The populated <code>ListSessions200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListSessions200Response();

            if (data.hasOwnProperty('sessions')) {
                obj['sessions'] = ApiClient.convertToType(data['sessions'], [Session]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListSessions200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListSessions200Response</code>.
     */
    static validateJSON(data) {
        if (data['sessions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['sessions'])) {
                throw new Error("Expected the field `sessions` to be an array in the JSON data but got " + data['sessions']);
            }
            // validate the optional field `sessions` (array)
            for (const item of data['sessions']) {
                Session.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Session>} sessions
 */
ListSessions200Response.prototype['sessions'] = undefined;






export default ListSessions200Response;

