/**
 * Auth Service API
 * Authentication Service for the Transcendence Pong application. Handles JWT tokens, OAuth2/SSO, and session management. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RevokeAllSessions200Response model module.
 * @module model/RevokeAllSessions200Response
 * @version 1.0.0
 */
class RevokeAllSessions200Response {
    /**
     * Constructs a new <code>RevokeAllSessions200Response</code>.
     * @alias module:model/RevokeAllSessions200Response
     */
    constructor() { 
        
        RevokeAllSessions200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RevokeAllSessions200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RevokeAllSessions200Response} obj Optional instance to populate.
     * @return {module:model/RevokeAllSessions200Response} The populated <code>RevokeAllSessions200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RevokeAllSessions200Response();

            if (data.hasOwnProperty('revokedCount')) {
                obj['revokedCount'] = ApiClient.convertToType(data['revokedCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RevokeAllSessions200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RevokeAllSessions200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Number of sessions revoked
 * @member {Number} revokedCount
 */
RevokeAllSessions200Response.prototype['revokedCount'] = undefined;






export default RevokeAllSessions200Response;

