openapi: 3.1.0
info:
  title: Auth Service API
  description: |
    Authentication Service for the Transcendence Pong application.
    Handles JWT tokens, OAuth2/SSO, and session management.
  version: 1.0.0
  contact:
    name: Transcendence Team
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /api/v1
    description: API Gateway endpoint

tags:
  - name: Authentication
    description: Login and registration endpoints
  - name: OAuth
    description: OAuth2/SSO authentication
  - name: Session
    description: Session and token management

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Create a new user account with email and password
      operationId: register
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: Email or username already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login with credentials
      description: Authenticate user with email/username and password
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many login attempts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/logout:
    post:
      tags:
        - Session
      summary: Logout user
      description: Invalidate the current session and refresh token
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logout successful
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/refresh:
    post:
      tags:
        - Session
      summary: Refresh access token
      description: Get a new access token using a valid refresh token
      operationId: refreshToken
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/verify:
    get:
      tags:
        - Session
      summary: Verify access token
      description: Verify the current access token is valid
      operationId: verifyToken
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenInfo'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/password/forgot:
    post:
      tags:
        - Authentication
      summary: Request password reset
      description: Send a password reset email to the user
      operationId: forgotPassword
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '202':
          description: Password reset email sent (if account exists)
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/password/reset:
    post:
      tags:
        - Authentication
      summary: Reset password
      description: Reset password using a valid reset token
      operationId: resetPassword
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset successful
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Invalid or expired reset token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/password/change:
    post:
      tags:
        - Authentication
      summary: Change password
      description: Change password for authenticated user
      operationId: changePassword
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  # OAuth2 endpoints
  /auth/oauth/{provider}:
    get:
      tags:
        - OAuth
      summary: Initiate OAuth login
      description: Redirect to OAuth provider for authentication
      operationId: initiateOAuth
      security: []
      parameters:
        - name: provider
          in: path
          required: true
          description: OAuth provider name
          schema:
            type: string
            enum: [google, github, fortytwo]
        - name: redirect_uri
          in: query
          description: URL to redirect after authentication
          schema:
            type: string
            format: uri
      responses:
        '302':
          description: Redirect to OAuth provider
          headers:
            Location:
              description: OAuth provider authorization URL
              schema:
                type: string
                format: uri
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/oauth/{provider}/callback:
    get:
      tags:
        - OAuth
      summary: OAuth callback
      description: Handle OAuth provider callback after authentication
      operationId: oauthCallback
      security: []
      parameters:
        - name: provider
          in: path
          required: true
          description: OAuth provider name
          schema:
            type: string
            enum: [google, github, fortytwo]
        - name: code
          in: query
          required: true
          description: Authorization code from OAuth provider
          schema:
            type: string
        - name: state
          in: query
          required: true
          description: State parameter for CSRF protection
          schema:
            type: string
      responses:
        '302':
          description: Redirect to application with tokens
          headers:
            Location:
              description: Application URL with auth tokens
              schema:
                type: string
                format: uri
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: OAuth authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  # Two-Factor Authentication
  /auth/2fa/enable:
    post:
      tags:
        - Session
      summary: Enable 2FA
      description: Generate 2FA secret and QR code for setup
      operationId: enable2FA
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 2FA setup initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TwoFactorSetup'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: 2FA already enabled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/2fa/verify:
    post:
      tags:
        - Session
      summary: Verify 2FA code
      description: Verify TOTP code to complete 2FA setup or login
      operationId: verify2FA
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - code
              properties:
                code:
                  type: string
                  pattern: '^[0-9]{6}$'
                  description: 6-digit TOTP code
      responses:
        '200':
          description: 2FA verified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          description: Invalid 2FA code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/2fa/disable:
    post:
      tags:
        - Session
      summary: Disable 2FA
      description: Disable two-factor authentication
      operationId: disable2FA
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - code
                - password
              properties:
                code:
                  type: string
                  pattern: '^[0-9]{6}$'
                  description: Current 6-digit TOTP code
                password:
                  type: string
                  description: Current password for confirmation
      responses:
        '200':
          description: 2FA disabled successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  # Session management
  /auth/sessions:
    get:
      tags:
        - Session
      summary: List active sessions
      description: Get all active sessions for the current user
      operationId: listSessions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of active sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Session'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/sessions/{sessionId}:
    delete:
      tags:
        - Session
      summary: Revoke session
      description: Revoke a specific session
      operationId: revokeSession
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Session revoked successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /auth/sessions/revoke-all:
    post:
      tags:
        - Session
      summary: Revoke all sessions
      description: Revoke all sessions except the current one
      operationId: revokeAllSessions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: All other sessions revoked
          content:
            application/json:
              schema:
                type: object
                properties:
                  revokedCount:
                    type: integer
                    description: Number of sessions revoked
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - username
        - password
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        username:
          type: string
          minLength: 3
          maxLength: 20
          pattern: '^[a-zA-Z0-9_]+$'
        password:
          type: string
          minLength: 8
          maxLength: 128
          description: Must contain at least one uppercase, lowercase, number, and special character
        displayName:
          type: string
          maxLength: 50

    LoginRequest:
      type: object
      required:
        - identifier
        - password
      properties:
        identifier:
          type: string
          description: Email or username
        password:
          type: string

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
        refreshToken:
          type: string
          description: Refresh token for obtaining new access tokens
        tokenType:
          type: string
          default: Bearer
        expiresIn:
          type: integer
          description: Access token expiration time in seconds
        user:
          $ref: '#/components/schemas/UserInfo'
        requires2FA:
          type: boolean
          description: Whether 2FA verification is required to complete login

    RefreshTokenRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          type: string

    ResetPasswordRequest:
      type: object
      required:
        - token
        - password
      properties:
        token:
          type: string
          description: Password reset token from email
        password:
          type: string
          minLength: 8
          maxLength: 128

    ChangePasswordRequest:
      type: object
      required:
        - currentPassword
        - newPassword
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string
          minLength: 8
          maxLength: 128

    TokenInfo:
      type: object
      properties:
        valid:
          type: boolean
        userId:
          type: string
          format: uuid
        username:
          type: string
        expiresAt:
          type: string
          format: date-time
        issuedAt:
          type: string
          format: date-time

    UserInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        username:
          type: string
        displayName:
          type: string
        avatarUrl:
          type: string
          format: uri
        has2FAEnabled:
          type: boolean

    TwoFactorSetup:
      type: object
      properties:
        secret:
          type: string
          description: TOTP secret key
        qrCodeUrl:
          type: string
          format: uri
          description: URL to QR code image for authenticator app
        backupCodes:
          type: array
          items:
            type: string
          description: One-time backup codes

    Session:
      type: object
      properties:
        id:
          type: string
          format: uuid
        deviceInfo:
          type: string
          description: Browser/device information
        ipAddress:
          type: string
        location:
          type: string
          description: Approximate geographic location
        createdAt:
          type: string
          format: date-time
        lastActiveAt:
          type: string
          format: date-time
        isCurrent:
          type: boolean
          description: Whether this is the current session

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code for client handling
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error details

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    Unauthorized:
      description: Authentication required or token invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
