/**
 * Auth Service API
 * Authentication Service for the Transcendence Pong application. Handles JWT tokens, OAuth2/SSO, and session management. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Verify2FARequest model module.
 * @module model/Verify2FARequest
 * @version 1.0.0
 */
class Verify2FARequest {
    /**
     * Constructs a new <code>Verify2FARequest</code>.
     * @alias module:model/Verify2FARequest
     * @param code {String} 6-digit TOTP code
     */
    constructor(code) { 
        
        Verify2FARequest.initialize(this, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code) { 
        obj['code'] = code;
    }

    /**
     * Constructs a <code>Verify2FARequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Verify2FARequest} obj Optional instance to populate.
     * @return {module:model/Verify2FARequest} The populated <code>Verify2FARequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Verify2FARequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Verify2FARequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Verify2FARequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Verify2FARequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }

        return true;
    }


}

Verify2FARequest.RequiredProperties = ["code"];

/**
 * 6-digit TOTP code
 * @member {String} code
 */
Verify2FARequest.prototype['code'] = undefined;






export default Verify2FARequest;

