// this file contains a test harness that was auto-generated by fastify-openapi-glue
// running the tests directly after generation will probably fail as the parameters
// need to be manually added.

import { test } from "node:test";
import Fastify from "fastify";
import fastifyPlugin from "../index.js";
import { Service } from "../service.js";
import { redisClient } from "../redisClient.js";
import assert from "node:assert";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
// import { GenericContainer, StartedTestContainer } from "testcontainers";
// const specification = "../openApi.json";

const ACCESS_TOKEN_TTL = 60 * 24; // 24h
const REFRESH_TOKEN_TTL = 60 * 60 * 24; // 24h in seconds

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const specification = join(__dirname, "../openApi.json");

const service = new Service();

const opts = {
	specification,
	service,
};

const uuid = "User1";
const username = "testuser";
const email = "test@test.fr";
const password = "Test1234!";
const displayName = "Test User";
const avatarUrl = "https://example.com/avatar.png";
const has2FAEnabled = false;
const currentPassword = "Test1234!";
const newPassword = "NewPass1234!";
const code = "123456";
const token = process.env.ACCESS_TOKEN;
const refreshToken = process.env.REFRESH_TOKEN;
const userKey = `user:${username}`;
const emailKey = `email:${email}`;

test("testing register", async (t) => {
	const fastify = Fastify();
	fastify.register(fastifyPlugin, opts);
	await fastify.ready();

	// Clear everything in the current database
	await redisClient.flushDb();

	const res = await fastify.inject({
		method: "POST",
		url: "/auth/register",
		payload: {
			username,
			displayName,
			password,
			email,
			avatarUrl,
			has2FAEnabled
		},
	});
	console.log(res.statusCode, res.payload);

	const stored = await redisClient.hGetAll(userKey);
	console.log("User stored in Redis: ", stored);

	assert.equal(res.statusCode, 201);
	await fastify.close();
	// await redisClient.quit();
});

test("testing login", async (t) => {
	const fastify = Fastify();
	fastify.register(fastifyPlugin, opts);
	await fastify.ready();

	const res = await fastify.inject({
		method: "POST",
		url: "/auth/login",
		payload: {
			identifier: username, // or email
			password,
		},
	});
	assert.equal(res.statusCode, 200);
	await fastify.close();
	//await redisClient.quit();
});

test("testing logout", async (t) => {
	const fastify = Fastify();
	fastify.register(fastifyPlugin, opts);
	await fastify.ready();

	const res = await fastify.inject({
		method: "POST",
		url: "/auth/logout",
		headers: {
			authorization: `Bearer ${token}`,
		}
	});
	console.log(res.statusCode, res.payload);
	assert.equal(res.statusCode, 204);
	await fastify.close();
	// await redisClient.quit();

	// Check that the token is blacklisted in Redis
	// const isBlacklisted = await redisClient.get(`blacklist:${token}`);
	// console.log("Blacklisted: ", isBlacklisted);
	// assert.equal(isBlacklisted, "1");
});

test("testing refresh token", async () => {
	const fastify = Fastify();
	fastify.register(fastifyPlugin, opts);
	await fastify.ready();

	const res = await fastify.inject({
		method: "POST",
		url: "/auth/refresh",
		payload: { refreshToken },
	});
	assert.equal(res.statusCode, 200);
	await fastify.close();
	await redisClient.quit();

	// const oldTokenExists = await redisClient.exists(`refresh:${refreshToken}`);
	// assert.equal(oldTokenExists, 0); // old token must be revoked

	// const newTokenExists = await redisClient.exists(
	// 	`refresh:${body.refreshToken}`
	// );
	// assert.equal(newTokenExists, 1); // new token must exist
});


// test("testing verifyToken", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "GET",
// 		url: "/auth/verify",
// 		headers: {
// 			authorization: `Bearer ${token}`,
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing forgotPassword", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);
// 	await fastify.ready();

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/password/forgot",
// 		payload: {
// 			email
// 		},
// 	});
// 	assert.equal(res.statusCode, 202);
// });

// // test("testing resetPassword", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "POST",
// // 		url: "/auth/password/reset",
// // 		payload: {
// // 			token,
// // 			password
// // 		},
// // 	});
// // 	t.assert.equal(res.statusCode, 200);
// // });

// // test("testing changePassword", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "POST",
// // 		url: "/auth/password/change",
// // 		payload: {
// // 			currentPassword,
// // 			newPassword,
// // 		},
// // 		headers: {
// // 			authorization: `Bearer ${token}`,
// // 		},
// // 	});
// // 	t.assert.equal(res.statusCode, 200);
// // });

// // test("testing initiateOAuth", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "GET",
// // 		//url: "/auth/oauth/:provider",
// // 		url: "/auth/oauth/google?redirect_uri=https://example.com/callback",
// // 	});
// // 	t.assert.equal(res.statusCode, 302);
// // });

// // test("testing oauthCallback", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "GET",
// // 		// url: "/auth/oauth/:provider/callback",
// // 		url: "/auth/oauth/google/callback?code=abcd1234&state=xyz",
// // 	});
// // 	t.assert.equal(res.statusCode, 302);
// // });

// test("enable2FA returns QR code and backup codes", async () => {
// 	const fastify = Fastify();
//   const res = await fastify.inject({
//     method: "POST",
//     url: "/auth/2fa/enable",
//     headers: {
//       authorization: `Bearer ${token}`,
//     },
//   });

//   assert.equal(res.statusCode, 200);

//   const body = JSON.parse(res.payload);
//   assert.ok(body.secret);
//   assert.ok(body.qrCodeUrl);
//   assert.equal(body.backupCodes.length, 8);
// });

// test("enable2FA fails if already enabled", async () => {
//   await redisClient.hSet(`user:${username}`, {
//     has2FAEnabled: "true",
//   });

//   const res = await fastify.inject({
//     method: "POST",
//     url: "/auth/2fa/enable",
//     headers: {
//       authorization: `Bearer ${accessToken}`,
//     },
//   });

//   assert.equal(res.statusCode, 409);
// });

// // test("testing verify2FA", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "POST",
// // 		url: "/auth/2fa/verify",
// // 		payload: {
// // 			code
// // 		},
// // 		headers: {
// // 			authorization: `Bearer ${token}`
// // 		},
// // 	});
// // 	t.assert.equal(res.statusCode, 200);
// // });

// test("verify2FA activates 2FA", async () => {
//   const secret = speakeasy.generateSecret();
//   const token = speakeasy.totp({
//     secret: secret.base32,
//     encoding: "base32",
//   });

//   await redisClient.hSet(`2fa:pending:${username}`, {
//     secret: secret.base32,
//     backupCodes: "[]",
//   });

//   const res = await fastify.inject({
//     method: "POST",
//     url: "/auth/2fa/verify",
//     headers: { authorization: `Bearer ${accessToken}` },
//     payload: { code: token },
//   });

//   assert.equal(res.statusCode, 200);
// });

// // test("testing disable2FA", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "POST",
// // 		url: "/auth/2fa/disable",
// // 		payload: {
// // 			code,
// // 			password
// // 		},
// // 		headers: {
// // 			authorization: `Bearer ${token}`
// // 		},
// // 	});
// // 	t.assert.equal(res.statusCode, 200);
// // });

// // test("testing listSessions", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "GET",
// // 		url: "/auth/sessions",
// // 	});
// // 	t.assert.equal(res.statusCode, 200);
// // });

// // test("testing revokeSession", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const sessionId = "00000000-0000-0000-0000-000000000000";

// // 	const res = await fastify.inject({
// // 		method: "DELETE",
// // 		// url: "/auth/sessions/:sessionId",
// // 		url: `/auth/sessions/${sessionId}`,
// // 		headers: {
// // 			authorization: `Bearer ${token}`
// // 		},
// // 	});
// // 	t.assert.equal(res.statusCode, 204);
// // });

// // test("testing revokeAllSessions", async (t) => {
// // 	const fastify = Fastify();
// // 	fastify.register(fastifyPlugin, opts);

// // 	const res = await fastify.inject({
// // 		method: "POST",
// // 		url: "/auth/sessions/revoke-all",
// // 		headers: {
// // 			authorization: `Bearer ${token}`
// // 		},
// // 	});
// // 	t.assert.equal(res.statusCode, 200);
// // });
