// this file contains a test harness that was auto-generated by fastify-openapi-glue
// running the tests directly after generation will probably fail as the parameters
// need to be manually added.


import { test } from "node:test";
import Fastify from "fastify";
import fastifyPlugin from "../index.js";
import { Service } from "../service.js";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
// import { GenericContainer, StartedTestContainer } from "testcontainers";

// const specification = "../openApi.json";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const specification = join(__dirname, "../openApi.json");

const service = new Service();

const opts = {
	specification,
	service,
};

const token = "MY_JWT";
const username = "testuser";
const email = "test@test.fr";
const password = "Test1234!";
const displayName = "Test User";
const avatar = "https://example.com/avatar.png";
const enable2FA = false;
const currentPassword = "Test1234!";
const newPassword = "NewPass1234!";
const code = "123456";
const refreshToken = "MY_REFRESH_TOKEN";

test("testing register", async (t) => {
	const fastify = Fastify();
	fastify.register(fastifyPlugin, opts);

	// await fastify.ready();

	const res = await fastify.inject({
		method: "POST",
		url: "/auth/register",
		payload: {
			username,
			displayName,
			password,
			email,
			avatar,
			enable2FA
		},
	});
	console.log(res.statusCode, res.payload);
	t.assert.equal(res.statusCode, 201);
});

// test("testing login", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/login",
// 		payload: {
// 			identifier: username, // or email
// 			password,
// 		},
// 	});
// 	console.log(res.statusCode, res.payload);
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing logout", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/logout",
// 		headers: {
// 			authorization: `Bearer ${token}`,
// 		}
// 	});
// 	console.log(res.statusCode, res.payload);
// 	t.assert.equal(res.statusCode, 204);
// });

// test("testing refreshToken", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/refresh",
// 		payload: {
// 			refreshToken
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing verifyToken", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "GET",
// 		url: "/auth/verify",
// 		headers: {
// 			authorization: `Bearer ${token}`,
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing forgotPassword", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/password/forgot",
// 		payload: {
// 			email
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 202);
// });

// test("testing resetPassword", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/password/reset",
// 		payload: {
// 			token,
// 			password
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing changePassword", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/password/change",
// 		payload: {
// 			currentPassword,
// 			newPassword,
// 		},
// 		headers: {
// 			authorization: `Bearer ${token}`,
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing initiateOAuth", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "GET",
// 		//url: "/auth/oauth/:provider",
// 		url: "/auth/oauth/google?redirect_uri=https://example.com/callback",
// 	});
// 	t.assert.equal(res.statusCode, 302);
// });

// test("testing oauthCallback", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "GET",
// 		// url: "/auth/oauth/:provider/callback",
// 		url: "/auth/oauth/google/callback?code=abcd1234&state=xyz",
// 	});
// 	t.assert.equal(res.statusCode, 302);
// });

// test("testing enable2FA", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/2fa/enable",
// 		headers: {
// 			authorization: `Bearer ${token}`,
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing verify2FA", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/2fa/verify",
// 		payload: {
// 			code
// 		},
// 		headers: {
// 			authorization: `Bearer ${token}`
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing disable2FA", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/2fa/disable",
// 		payload: {
// 			code,
// 			password
// 		},
// 		headers: {
// 			authorization: `Bearer ${token}`
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing listSessions", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "GET",
// 		url: "/auth/sessions",
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });

// test("testing revokeSession", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const sessionId = "00000000-0000-0000-0000-000000000000";

// 	const res = await fastify.inject({
// 		method: "DELETE",
// 		// url: "/auth/sessions/:sessionId",
// 		url: `/auth/sessions/${sessionId}`,
// 		headers: {
// 			authorization: `Bearer ${token}`
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 204);
// });

// test("testing revokeAllSessions", async (t) => {
// 	const fastify = Fastify();
// 	fastify.register(fastifyPlugin, opts);

// 	const res = await fastify.inject({
// 		method: "POST",
// 		url: "/auth/sessions/revoke-all",
// 		headers: {
// 			authorization: `Bearer ${token}`
// 		},
// 	});
// 	t.assert.equal(res.statusCode, 200);
// });
